### ISSUE TITLE
Faraday adds brackets to LOC queries

### ISSUE THREAD

**Issue by NedHenry** [projecthydra-labs/questioning_authority#101]
Modern versions of Faraday (which is used to query the LOC endpoints) automatically add brackets to repeated query parameters. In other words, 
`http://id.loc.gov/search/?q=query&q=cs:http://etc.gov`
becomes
`http://id.loc.gov/search/?q[]=query&q[]=cs:http://etc.gov`
This causes my queries to be misinterpreted, so I get the same response from every LOC query no matter which subauthority or query string I use. 
[Here is the faraday issue addressing this issue.](https://github.com/lostisland/faraday/issues/182)

**Comment by mjgiarlo** [comment]
Closed by #129, I believe.
