### ISSUE TITLE
Table generator does invalid substitution.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/questioning_authority#130]
I see this generated in the `CreateQaLocalAuthorityEntries` migration:
`      t.references :local_authority, foreign_key: true`

but this is the first argument of the gsub in the tables_generator:
 `'t.references :local_authority, index: true, foreign_key: true'`

I don't know why it's trying to match that `index: true`. Perhaps that's a rails 4 thing or a mysql only thing, but we should see if we can do the substitution in a way that matches all cases.

Reported by @acozine

**Comment by acozine** [comment]
The error I was seeing was:
```
== 20170115055904 CreateQaLocalAuthorityEntries: migrating ====================
-- create_table(:qa_local_authority_entries)
rake stderr: rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "local_authorities" does not exist
: CREATE TABLE "qa_local_authority_entries" ("id" serial primary key, "local_authority_id" integer, "label" character varying, "uri" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_cee742275b"
FOREIGN KEY ("local_authority_id")
  REFERENCES "local_authorities" ("id")
)
```
I manually changed `:local_authority` to `:qa_local_authority` in the migration in my generated app, and the migration succeeded.
