### ISSUE TITLE
LOC response always returns the same JSON 

### ISSUE THREAD

**Issue by little9** [projecthydra-labs/questioning_authority#133]
I've tested qa 0.11.0 on Rails 4 & 5 and whenever I do an LOC request it always returns this JSON: 

Here's the response for http://localhost:3000/qa/search/loc/subjects?q=China 

```json
[{"id":"info:lc/authorities/subjects/sh2010112128","label":"School sports--Fiction"},{"id":"info:lc/authorities/subjects/sh2008001841","label":"Private flying--Accidents--United States--Periodicals"},{"id":"info:lc/authorities/subjects/sh93000006","label":"Costa Rica--History--1986-"},{"id":"info:lc/authorities/subjects/sh2008116817","label":"Zimbabwe--Economic policy"},{"id":"info:lc/authorities/subjects/sh00008433","label":"Reinstatement"},{"id":"info:lc/authorities/subjects/sh85113459","label":"Revolutionary literature, Portuguese"},{"id":"info:lc/authorities/subjects/sh2003009896","label":"Herbicides--Physiological effect"},{"id":"info:lc/authorities/subjects/sh2003006908","label":"Hôtel de ville (Tours, France)"},{"id":"info:lc/authorities/subjects/sh2010010320","label":"Skin--Cancer--Risk factors--Congresses"},{"id":"info:lc/authorities/subjects/sh85095974","label":"Osteopathic students"},{"id":"info:lc/authorities/subjects/sh2007005866","label":"Face--Muscles--Abnormalities--Treatment"},{"id":"info:lc/authorities/subjects/sh85062079","label":"Horror in art"},{"id":"info:lc/authorities/subjects/sh85008524","label":"Tailed frog"},{"id":"info:lc/authorities/subjects/sh97009005","label":"Apocryphal books (New Testament)--Criticism, interpretation, etc"},{"id":"info:lc/authorities/subjects/sh85011651","label":"Banks and banking, Cooperative"},{"id":"info:lc/authorities/subjects/sh85058833","label":"Harbor masthttp://id.loc.gov/search/?q=China&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects&format=json
ers"},{"id":"info:lc/authorities/subjects/sh85126627","label":"Poisonous spiders--Venom"},{"id":"info:lc/authorities/subjects/sh2001009695","label":"Trachyphloeus"},{"id":"info:lc/authorities/subjects/sh85061960","label":"Hopwood family"},{"id":"info:lc/authorities/subjects/sh92003912","label":"Polányi family"}]
```

Internally it's making this request: 

http://id.loc.gov/search/?q=China&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects&format=json

**Comment by jcoyne** [comment]
@little9 what behavior are you expecting?

**Comment by jcoyne** [comment]
This appears to be the behavior that is expected in the tests: https://github.com/projecthydra-labs/questioning_authority/blob/43cba871eda61b55096321e10e486254762f939e/spec/lib/authorities/loc_spec.rb#L31

**Comment by little9** [comment]
I always get the same results regardless of the term. So these all return the same 
results:

http://localhost:3000/qa/search/loc/subjects?q=History
http://localhost:3000/qa/search/loc/subjects?q=China 
http://localhost:3000/qa/search/loc/subjects?q=Wu

'School sports--Fiction' is always the first result.

**Comment by jcoyne** [comment]
@little9 have you tried master? Has this patch changed anything? https://github.com/projecthydra-labs/questioning_authority/commit/bf86ac124fbd1952393862a98c598e1515620d40

**Comment by little9** [comment]
That didn't fix the issue for me. I think this is caused by Faraday dropping one of the params in the LOC query. The LOC query uses ?q twice and Faraday drops the first one resulting in this URL: 

http://id.loc.gov/search/?q=&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects&format=json

The first result is the 'School sports -- Fiction' result that I'm getting. 

I'll refactor this a bit and submit a PR.

**Comment by no-reply** [comment]
Is this issue closed via #134?

**Comment by little9** [comment]
It was already fixed on the master branch, the gem just needs to be updated

**Comment by little9** [comment]
The gem was updated so this can be closed.
