### ISSUE TITLE
RestClient::ResourceNotFound should return 404, not 500

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/questioning_authority#75]

**Comment by awead** [comment]
@jcoyne where are you seeing that?

**Comment by jcoyne** [comment]
@awead This can probably be closed as irrelevant. This was caused by hitting Getty's api with a request it mishandles and returns a 404. This raises an unhandled RestClient::ResourceNotFound exception, which rails passes to the consumer as a 500 error.
